# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('C:/Users/Ghanendra/Desktop/Churn1.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[0 'Female' 'Yes' ... 'Electronic check' 29.85 '29.85']
 [0 'Male' 'No' ... 'Mailed check' 56.95 '1889.5']
 [0 'Male' 'No' ... 'Mailed check' 53.85 '108.15']
 ...
 [0 'Female' 'Yes' ... 'Electronic check' 29.6 '346.45']
 [1 'Male' 'Yes' ... 'Mailed check' 74.4 '306.6']
 [0 'Male' 'No' ... 'Bank transfer (automatic)' 105.65 '6844.5']]


In [4]:
X[:, -1] = pd.to_numeric(X[:,-1], errors='coerce')


In [5]:
print(X)

[[0 'Female' 'Yes' ... 'Electronic check' 29.85 29.85]
 [0 'Male' 'No' ... 'Mailed check' 56.95 1889.5]
 [0 'Male' 'No' ... 'Mailed check' 53.85 108.15]
 ...
 [0 'Female' 'Yes' ... 'Electronic check' 29.6 346.45]
 [1 'Male' 'Yes' ... 'Mailed check' 74.4 306.6]
 [0 'Male' 'No' ... 'Bank transfer (automatic)' 105.65 6844.5]]


In [6]:
print(y)

['No' 'No' 'Yes' ... 'No' 'Yes' 'No']


### Encoding categorical data

# Encoding the Independent Variable

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in range(1,6):
    X[:, i] = le.fit_transform(X[:, i])

In [8]:
print(X)

[[0 0 1 ... 'Electronic check' 29.85 29.85]
 [0 1 0 ... 'Mailed check' 56.95 1889.5]
 [0 1 0 ... 'Mailed check' 53.85 108.15]
 ...
 [0 0 1 ... 'Electronic check' 29.6 346.45]
 [1 1 1 ... 'Mailed check' 74.4 306.6]
 [0 1 0 ... 'Bank transfer (automatic)' 105.65 6844.5]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [11])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [14])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [17])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [20])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [23])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [15]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [26])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [16]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [29])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [32])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [18]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [35])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [19]:
print(X[487, :])

[0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0
 1.0 0.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 0 1 0 0 1 1 72 88.6
 6201.95]


# Taking care of missing data

In [20]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[:, 39:40])
X[:, 39:40] = imputer.transform(X[:, 39:40])

In [21]:
print(X[487, :])

[0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0
 1.0 0.0 0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 0 1 0 0 1 1 72 88.6
 6201.95]


# Encoding the Dependent Variable

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [23]:
print(y)

[0 0 1 ... 0 1 0]


# Splitting the dataset into the Training set and Test set 

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.432)

### Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [26]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [27]:
ann.add(tf.keras.layers.Dense(units=22, activation='relu'))

### Adding the second hidden layer

In [28]:
ann.add(tf.keras.layers.Dense(units=22, activation='relu'))

In [29]:
ann.add(tf.keras.layers.Dense(units=22, activation='relu'))

In [30]:
ann.add(tf.keras.layers.Dense(units=22, activation='relu'))

### Adding the output layer

In [31]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [32]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [33]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 25)

Epoch 1/25
125/125 [==============================] - 1s 954us/step - loss: 0.5546 - accuracy: 0.7152
Epoch 2/25
125/125 [==============================] - 0s 808us/step - loss: 0.4519 - accuracy: 0.7734
Epoch 3/25
125/125 [==============================] - 0s 934us/step - loss: 0.4412 - accuracy: 0.7817
Epoch 4/25
125/125 [==============================] - 0s 934us/step - loss: 0.4202 - accuracy: 0.8033
Epoch 5/25
125/125 [==============================] - 0s 934us/step - loss: 0.4339 - accuracy: 0.7913
Epoch 6/25
125/125 [==============================] - 0s 934us/step - loss: 0.4091 - accuracy: 0.8032
Epoch 7/25
125/125 [==============================] - 0s 934us/step - loss: 0.4204 - accuracy: 0.7975
Epoch 8/25
125/125 [==============================] - 0s 934us/step - loss: 0.4080 - accuracy: 0.8017
Epoch 9/25
125/125 [==============================] - 0s 808us/step - loss: 0.4253 - accuracy: 0.7977
Epoch 10/25
125/125 [==============================] - 0s 808us/step - loss: 0.414

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [34]:
y_pred = ann.predict(sc.transform(X_test))
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


### Making the Confusion Matrix

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2068  178]
 [ 527  270]]


0.7683207361156753